### ISSUE TITLE
dont forget to add trim to policy if you want to use this method

### ISSUE THREAD

**Issue by elmagekmosaad** [tgolla/TGolla.Swashbuckle.AspNetCore#2]
please dont forget to add trim to policy
if you want to use this method
[https://github.com/tgolla/TGolla.Swashbuckle.AspNetCore/blob/main/TGolla.AspNetCore.Mvc.Filters/Readme.md](url)

because if you forget and add a space, the process will fail and it will appear to you that the policy does not exist
I faced this problem myself now and solved it by trimming the policy on this line
var authorized = await authorization.AuthorizeAsync(context.HttpContext.User, policy.Trim());
I changed it from
var authorized = await authorization.AuthorizeAsync(context.HttpContext.User, policy);
to
var authorized = await authorization.AuthorizeAsync(context.HttpContext.User, policy.Trim());
To avoid the problem when using blanks such as
[AuthorizeOnAnyOnePolicy($"{Policies.Admin}, {Policies.Employee}")]

**Comment by tgolla** [comment]
@elmagekmosaad I will look into this.

**Comment by tgolla** [comment]
@elmagekmosaad Planning on releasing a code solution later this weekend with a more elegant refactor. 
var policies = Policies.Split(",", StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries).ToList();
Always try to enforce a business rule at the source. Thanks for pointing this out.

**Comment by tgolla** [comment]
Release 6.0.0 resolves this issue. https://github.com/tgolla/TGolla.Swashbuckle.AspNetCore/discussions/4
